In [2]:
import numpy as np

In [6]:
res_1 = np.arange(1, 10+1)
print(res_1)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
res_2 = np.zeros((3, 3))
print(res_2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
res_3 = np.random.randint(1, 10, (5, 5))
print(res_3)

[[8 6 9 1 3]
 [6 3 1 5 9]
 [5 7 6 5 5]
 [1 3 2 5 3]
 [9 1 9 5 8]]


In [11]:
res_4 = np.random.random((4, 4))
print(res_4)

[[0.52343568 0.15555594 0.8906888  0.32778273]
 [0.2377826  0.06306955 0.74442107 0.27962089]
 [0.64109373 0.54232003 0.26749796 0.99229686]
 [0.03576231 0.384439   0.07062226 0.39706506]]


In [18]:
# 5
a = np.random.randint(1, 10, (5,))
b = np.random.randint(1, 10, (5,))
print(a + b)
print(a - b)
print(a * b)

[ 9 12  8  9  9]
[-7 -2 -2  1  3]
[ 8 35 15 20 18]


In [24]:
# 6
a = np.random.randint(1, 10, (7,))
b = np.random.randint(1, 10, (7,))
print(np.dot(a, b))

152


In [26]:
# 7
a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 3))
print(np.dot(a, b))

[[52 65 37]
 [37 44 31]]


In [29]:
# 8
a = np.random.random((4,4))
a_inv = np.linalg.inv(a)
print(a_inv)

[[  2.84175136  -1.03052388  -3.74717687   2.33834579]
 [  1.42355678  -1.41524295  -3.72733927   4.31569361]
 [  3.95843071  -3.65139873  -5.48002517   5.7679094 ]
 [ -7.29968118   6.55290523  12.61789992 -11.60243606]]


In [30]:
# 9
a = np.random.random((4,4))
print(a.T)

[[0.6915924  0.54138627 0.29879006 0.1594655 ]
 [0.0116615  0.50101129 0.4498798  0.43815448]
 [0.83606704 0.00279545 0.74393612 0.83543224]
 [0.03613718 0.10442937 0.48165567 0.67200798]]


In [32]:
# 10
a = np.random.randint(1, 10, (3, 4))
b = np.random.randint(1, 10, (4,))
print(a, b)
print(a * b)

[[4 9 8 2]
 [9 5 2 2]
 [2 7 1 2]] [9 1 3 3]
[[36  9 24  6]
 [81  5  6  6]
 [18  7  3  6]]


In [35]:
# 11
a = np.random.random((2, 3))
b = np.random.random((3,))
print(a, b)
print(a * b)

[[0.06513963 0.90885725 0.271198  ]
 [0.00511453 0.95652269 0.6618694 ]] [0.20085081 0.4955617  0.65614075]
[[0.01308335 0.45039484 0.17794406]
 [0.00102726 0.47401601 0.43427949]]


In [37]:
# 12
a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 2))
print(a * b)

[[36 56]
 [56  8]]


In [40]:
# 13
a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 2))
print(np.dot(a, b))

[[80 88]
 [18 14]]


In [43]:
# 14
a = np.random.randint(1, 100, (5, 5))
print(a.sum())

1223


In [45]:
# 15
a = np.random.randint(1, 10, (4, 4))
b = np.random.randint(1, 10, (4, 4))
print(a -  b)

[[ 4  0  0  5]
 [-1 -2  4  0]
 [-1 -4  1  6]
 [-6  1  5  0]]


In [53]:
#16
a = np.random.random((3, 3))
print(a)
b = np.array([i.sum() for i in a])
print(b)

[[0.29846498 0.85012149 0.17392847]
 [0.77877186 0.8559984  0.25254004]
 [0.0821756  0.24577655 0.83910149]]
[1.32251493 1.8873103  1.16705365]


In [57]:
# 17
a = np.random.randint(1, 10, (3, 4))
print(a)
b = np.array([[j**2 for j in i] for i in a])
print(b)

[[9 6 1 1]
 [9 6 8 1]
 [9 8 4 5]]
[[81 36  1  1]
 [81 36 64  1]
 [81 64 16 25]]


In [58]:
# 18
a = np.random.randint(1, 50, (4,))
print(a)
b = np.array([i**0.5 for i in a])
print(b)


[31 16  6  8]
[5.56776436 4.         2.44948974 2.82842712]
