In [12]:
import numpy as np

In [13]:
res_1 = np.arange(1, 10+1)
print(res_1)

[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
res_2 = np.zeros((3, 3))
print(res_2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
res_3 = np.random.randint(1, 10, (5, 5))
print(res_3)

[[8 9 3 1 3]
 [5 7 3 9 7]
 [3 1 3 7 8]
 [3 1 1 4 1]
 [1 8 1 3 8]]


In [16]:
res_4 = np.random.random((4, 4))
print(res_4)

[[0.02171841 0.10975203 0.5418889  0.85329246]
 [0.21662533 0.60248426 0.78464068 0.16273529]
 [0.99875375 0.71374869 0.0857337  0.22801712]
 [0.28390772 0.09363596 0.50201216 0.96873465]]


In [17]:
# 5
a = np.random.randint(1, 10, (5,))
b = np.random.randint(1, 10, (5,))
print(a + b)
print(a - b)
print(a * b)

[ 6 12  8  7 10]
[-2  2  6 -5 -2]
[ 8 35  7  6 24]


In [18]:
# 6
a = np.random.randint(1, 10, (7,))
b = np.random.randint(1, 10, (7,))
print(np.dot(a, b))

114


In [19]:
# 7
a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 3))
print(np.dot(a, b))

[[78 55 42]
 [64 45 34]]


In [20]:
# 8
a = np.random.random((4,4))
a_inv = np.linalg.inv(a)
print(a_inv)

[[-1.39118057  1.00960785  0.24174155  1.29026434]
 [-0.93240108  2.25798622 -3.15562527  2.50648672]
 [ 1.77353839 -1.40943944  2.67361895 -3.48897847]
 [ 1.7348551  -2.03164117  0.60097456 -0.43447396]]


In [21]:
# 9
a = np.random.random((4,4))
print(a.T)

[[0.9778375  0.31341551 0.78362429 0.82230388]
 [0.37177469 0.50128363 0.13858107 0.6620127 ]
 [0.20164649 0.65497205 0.40433183 0.41481742]
 [0.60483352 0.20324361 0.12569083 0.8337381 ]]


In [22]:
# 10
a = np.random.randint(1, 10, (3, 4))
b = np.random.randint(1, 10, (4,))
print(a, b)
print(a * b)

[[2 7 5 2]
 [3 5 8 4]
 [2 4 6 9]] [1 4 6 6]
[[ 2 28 30 12]
 [ 3 20 48 24]
 [ 2 16 36 54]]


In [23]:
# 11
a = np.random.random((2, 3))
b = np.random.random((3,))
print(a, b)
print(a * b)

[[0.91665129 0.19132027 0.61102259]
 [0.33131131 0.95156009 0.09684664]] [0.10716396 0.7574517  0.57637487]
[[0.09823198 0.14491586 0.35217807]
 [0.03550463 0.72076081 0.05581997]]


In [24]:
# 12
a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 2))
print(a * b)

[[18  6]
 [16 10]]


In [25]:
# 13
a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 2))
print(np.dot(a, b))

[[34 17]
 [72 36]]


In [26]:
# 14
a = np.random.randint(1, 100, (5, 5))
print(a.sum())

1295


In [27]:
# 15
a = np.random.randint(1, 10, (4, 4))
b = np.random.randint(1, 10, (4, 4))
print(a -  b)

[[ 4  2  6 -1]
 [ 1  4  1  7]
 [ 3  2  1  1]
 [ 0 -1  0 -2]]


In [28]:
#16
a = np.random.random((3, 3))
print(a)
b = np.array([i.sum() for i in a])
print(b.reshape(3,1))

[[0.04833721 0.17572354 0.26705066]
 [0.31283176 0.04248942 0.21087482]
 [0.70603579 0.21958585 0.95873752]]
[[0.49111141]
 [0.56619599]
 [1.88435916]]


In [29]:
# 17
a = np.random.randint(1, 10, (3, 4))
print(a)
b = np.array([[j**2 for j in i] for i in a])
print(b)

[[4 6 3 3]
 [2 3 9 1]
 [9 2 1 5]]
[[16 36  9  9]
 [ 4  9 81  1]
 [81  4  1 25]]


In [30]:
# 18
a = np.random.randint(1, 50, (4,))
print(a)
b = np.array([i**0.5 for i in a])
print(b)


[40 24  8 12]
[6.32455532 4.89897949 2.82842712 3.46410162]
